params:
  model: 'efficientnet-b0'
  model_path: '../../models/modelV2.pth'
  batch_size: 32
  train_data_path: 'data/train'
  test_data_path: 'data/test'
  num_classes: 102
  epochs: 10
  learning_rate: 0.001